spring:
  application:
    name: auth-asymmetric-encryption
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true

app:
  security:
    jwt:
      access-token-expiration: 86400000 #24 hours for local testing, but I recommend 15 minutes for production
      refresh-token-expiration: 604800000
    disposable-emails:
      - 10minutemail.com
      - 20minutemail.com
      - 33mail.com
      - 5ymail.com
      - anonbox.com
      - guerrillamail.com
      - mailinator.com
      - maildrop.cc
      - mailnesia.com
      - moakt.com
      - my10minutemail.com
      - throwawaymail.com
      - trashmail.com
      - temp-mail.org
      - tempmail.com
      - yopmail.com